"""Add highly qualified prospecting fields

Revision ID: 43e508e64d15
Revises: 82ba74c1c322
Create Date: 2026-03-09 23:29:26.045768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43e508e64d15'
down_revision: Union[str, Sequence[str], None] = '82ba74c1c322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraping_jobs', sa.Column('user_value_proposition', sa.Text(), nullable=True))
    op.add_column('scraping_jobs', sa.Column('target_location', sa.String(), nullable=True))
    op.add_column('scraping_jobs', sa.Column('target_language', sa.String(), nullable=True))
    op.add_column('scraping_jobs', sa.Column('target_company_size', sa.String(), nullable=True))
    op.add_column('scraping_jobs', sa.Column('target_pain_points', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraping_jobs', 'target_pain_points')
    op.drop_column('scraping_jobs', 'target_company_size')
    op.drop_column('scraping_jobs', 'target_language')
    op.drop_column('scraping_jobs', 'target_location')
    op.drop_column('scraping_jobs', 'user_value_proposition')
    # ### end Alembic commands ###
