"""Add personalized prospecting fields

Revision ID: 82ba74c1c322
Revises: 
Create Date: 2026-03-09 23:22:22.524244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82ba74c1c322'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraping_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=True),
    sa.Column('requested_by', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('user_profession', sa.String(), nullable=True),
    sa.Column('target_niche', sa.String(), nullable=True),
    sa.Column('user_technologies', sa.JSON(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('filters_json', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('total_found', sa.Integer(), nullable=True),
    sa.Column('total_saved', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraping_jobs_id'), 'scraping_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_scraping_jobs_workspace_id'), 'scraping_jobs', ['workspace_id'], unique=False)
    op.create_table('prospects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('workspace_id', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('contact_page_url', sa.String(), nullable=True),
    sa.Column('form_detected', sa.Boolean(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('instagram_url', sa.String(), nullable=True),
    sa.Column('facebook_url', sa.String(), nullable=True),
    sa.Column('inferred_tech_stack', sa.JSON(), nullable=True),
    sa.Column('inferred_niche', sa.String(), nullable=True),
    sa.Column('generic_attributes', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('confidence_level', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['scraping_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prospects_domain'), 'prospects', ['domain'], unique=True)
    op.create_index(op.f('ix_prospects_id'), 'prospects', ['id'], unique=False)
    op.create_index(op.f('ix_prospects_workspace_id'), 'prospects', ['workspace_id'], unique=False)
    op.create_table('scraping_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['scraping_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraping_logs_id'), 'scraping_logs', ['id'], unique=False)
    op.create_table('prospect_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=True),
    sa.Column('signal_type', sa.String(), nullable=False),
    sa.Column('signal_value', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prospect_signals_id'), 'prospect_signals', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prospect_signals_id'), table_name='prospect_signals')
    op.drop_table('prospect_signals')
    op.drop_index(op.f('ix_scraping_logs_id'), table_name='scraping_logs')
    op.drop_table('scraping_logs')
    op.drop_index(op.f('ix_prospects_workspace_id'), table_name='prospects')
    op.drop_index(op.f('ix_prospects_id'), table_name='prospects')
    op.drop_index(op.f('ix_prospects_domain'), table_name='prospects')
    op.drop_table('prospects')
    op.drop_index(op.f('ix_scraping_jobs_workspace_id'), table_name='scraping_jobs')
    op.drop_index(op.f('ix_scraping_jobs_id'), table_name='scraping_jobs')
    op.drop_table('scraping_jobs')
    # ### end Alembic commands ###
