"""Add sales probability factors

Revision ID: 98b488db594e
Revises: 43e508e64d15
Create Date: 2026-03-09 23:34:08.915197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98b488db594e'
down_revision: Union[str, Sequence[str], None] = '43e508e64d15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospects', sa.Column('hiring_signals', sa.Boolean(), nullable=True))
    op.add_column('prospects', sa.Column('estimated_revenue_signal', sa.String(), nullable=True))
    op.add_column('prospects', sa.Column('has_active_ads', sa.Boolean(), nullable=True))
    op.add_column('scraping_jobs', sa.Column('user_past_successes', sa.JSON(), nullable=True))
    op.add_column('scraping_jobs', sa.Column('user_roi_metrics', sa.JSON(), nullable=True))
    op.add_column('scraping_jobs', sa.Column('target_budget_signals', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraping_jobs', 'target_budget_signals')
    op.drop_column('scraping_jobs', 'user_roi_metrics')
    op.drop_column('scraping_jobs', 'user_past_successes')
    op.drop_column('prospects', 'has_active_ads')
    op.drop_column('prospects', 'estimated_revenue_signal')
    op.drop_column('prospects', 'hiring_signals')
    # ### end Alembic commands ###
